---
- name: Ensure tag is specified
  hosts: windows
  gather_facts: no

  tasks:
    - fail:
        msg: Please run the playbook with a tag [present | absent]

- name: Disk Partition and Format
  hosts: windows
  gather_facts: no
  tags: present

  vars:
    raw_disk: no
    
  tasks:

    - name: Get Disk info
      win_shell: Get-Disk | Where-Object PartitionStyle -eq 'raw' | Initialize-Disk -PassThru
      register: disks
      when: raw_disk

#New-Partition -DiskNumber 1 -Size 5gb | Set-Partition -NewDriveLetter E
    - name: Create a partition with drive letter E and size 5 GiB
      win_partition:
        drive_letter: E
        partition_size: 5 GiB
        disk_number: 1
#Format-Volume -DriveLetter E -FileSystem NTFS -Full
    - name: Format Partition E
      win_format:
        drive_letter: E
        file_system: NTFS
        new_label: Formatted
        # full: yes (check for any bad sectors - takes much longer)
        
#New-Partition -DiskNumber 1 -UseMaximumSize | Set-Partition -NewDriveLetter F
    - name: Create a partition with drive letter F and size remaining space
      win_partition:
        drive_letter: F
        partition_size: -1
        disk_number: 1
#Format-Volume -DriveLetter F -FileSystem NTFS -Full
    - name: Format Partition F
      win_format:
        drive_letter: F
        file_system: NTFS
        new_label: Formatted
        # full: yes (check for any bad sectors - takes much longer)

#New-Partition -DiskNumber 2 -Size 5gb | Set-Partition -NewDriveLetter G
    - name: Create a partition with drive letter G and size 5 GiB
      win_partition:
        drive_letter: G
        partition_size: 5 GiB
        disk_number: 2
#Format-Volume -DriveLetter G -FileSystem NTFS -Full
    - name: Format Partition G
      win_format:
        drive_letter: G
        file_system: NTFS
        new_label: Formatted
        # full: yes (check for any bad sectors - takes much longer)

#New-Partition -DiskNumber 2 -UseMaximumSize | Set-Partition -NewDriveLetter H
    - name: Create a partition with drive letter H and size remaining space
      win_partition:
        drive_letter: H
        partition_size: -1
        disk_number: 2
#Format-Volume -DriveLetter H -FileSystem NTFS -Full
    - name: Format Partition
      win_format:
        drive_letter: H
        file_system: NTFS
        new_label: Formatted
        # full: yes (check for any bad sectors - takes much longer)

- name: Remove Disk Partitions
  hosts: windows
  gather_facts: no
  tags: absent

  tasks:
    - name: Wipe Partitions
      win_partition:
        disk_number: "{{ item[0] }}"
        partition_number: "{{ item[1] }}"
        state: absent
      with_nested:
        - [ '1', '2']
        - [ '2', '3']



    # - name: Initialize disks
    #   win_shell: Initialize-Disk -Number "{{ item }}"
    #   with_items:
    #     - 1
    #     - 2
    #   when: 
    #     - disks.stdout_lines[4].find('RAW') != -1
    #     - disks.stdout_lines[5].find('RAW') != -1

    # - name: Get Disk info
    #   win_shell: Get-Disk | Select-Object Number,PartitionStyle
    #   register: disks_after
    # - debug:
    #     var: disks_after.stdout_lines[3:-1]