---
- name: Ensure tag is specified
  hosts: windows
  gather_facts: no

  tasks:
    - fail:
        msg: Please run the playbook with a tag [present | absent]

- name: Install DHCP on Windows Server
  hosts: windows
  gather_facts: no
  tags: present
  
  tasks:
    - name: Install DHCP
      win_feature:
        name: DHCP
        state: present
      register: output

    - name: See if Reboot is required
      win_reboot:
      when: output.reboot_required

- name: Remove DHCP on Windows Server
  hosts: windows
  gather_facts: no
  tags: absent

    - name: Remove DHCP
      win_feature:
        name: DHCP
        state: absent
      register: output

    - name: See if Reboot is required
      win_reboot:
      when: output.reboot_required
      
# #Powershell DSC Equivalent 

# Configuration installDHCP
# {
#     Node localhost 
#     {
#         WindowsFeature DHCPServer {
#             Ensure = "Present"
#             Name = "DHCP"
#         }
#     }
# }

# #Following command generates a MOF file from the above config
# installDHCP

# #Execute the MOF file
# Start-DscConfiguration -Wait -Force -Path .\installDHCP -Verbose
