- name: Create VM
  delegate_to: localhost
  azure_rm_virtualmachine:
    resource_group: "{{ lab_name }}-{{ rg_name }}"
    name: "{{ inventory_hostname }}"
    vm_size: "{{ vm_size }}"
    tags: "{{ tag }}"
    admin_username: "{{ vm_user }}"
    ssh_password_enabled: false
    ssh_public_keys:
      - path: "/home/azureuser/.ssh/authorized_keys"
        key_data: "{{ key_data }}"
    network_interfaces: "{{ inventory_hostname }}-nic"
    image:
      offer: "{{ offer }}"
      publisher: "{{ publisher }}"
      sku: "{{ sku }}"
      version: "{{ version }}"
    os_type: "{{ os_type }}"
    managed_disk_type: Standard_LRS