---
- name: Include secrets when VM create
  include_vars: "{{playbook_dir }}/secrets.yaml"
  when: activity == 'create-vm'
- name: Run Lab Activity
  include_tasks: "{{ activity }}.yaml"
  when: activity is defined