- name: Create VM
  delegate_to: localhost
  azure_rm_virtualmachine:
    admin_username: '{{ vm_user }}'
    admin_password: "{{ vm_password }}"
    resource_group: "{{ lab_name }}-{{ rg_name }}"
    name: "{{ inventory_hostname }}"
    vm_size: "{{ vm_size }}"
    tags: "{{ tag }}"
    ssh_password_enabled: false
    network_interfaces: "{{ inventory_hostname }}-nic"
    image:
      offer: "{{ offer }}"
      publisher: "{{ publisher }}"
      sku: "{{ sku }}"
      version: "{{ version }}"
    os_type: "{{ os_type }}"
    managed_disk_type: Standard_LRS
  register: vm_output

- debug:
    var: azure_vm.name

- name: Create VM Extension
  delegate_to: localhost
  azure_rm_virtualmachine_extension:
    name: "winrm-extension"
    resource_group: "{{ lab_name }}-{{ rg_name }}"
    virtual_machine_name: "{{ azure_vm.name }}"
    publisher: Microsoft.Compute
    virtual_machine_extension_type: CustomScriptExtension
    type_handler_version: 1.9
    settings: '{"fileUris": ["https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1"],"commandToExecute": "powershell.exe -ExecutionPolicy ByPass -File ConfigureRemotingForAnsible.ps1 -ForceNewSSLCert -EnableCredSSP"}'
    auto_upgrade_minor_version: true